CREATE TABLE usertable(year INTEGER NOT NULL);

CREATE PROCEDURE Insert
   AS INSERT INTO usertable (year) VALUES (?);

CREATE PROCEDURE Select
   AS SELECT year FROM usertable WHERE year = ?;

CREATE PROCEDURE Delete
   AS DELETE FROM usertable WHERE year = ?;
   
CREATE PROCEDURE Update
   AS UPDATE usertable SET year = ? WHERE year = ?;

INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2015);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2016);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2017);
INSERT INTO usertable(year) VALUES(2015);
